### PR TITLE
add turkish translation file

### PR DESCRIPTION
**Pull request by berte**
Hello there,

Can you please, add Turkish translation file to the proejct?

### CODE REVIEW

**Comment by valr** [comment]
Sure.
I'm finalizing few stuffs to complete the translation preparation process and will include the your translation after.
Thanks already for the translation.

**Comment by berte** [comment]
You are welcome valr :)

**Comment by valr** [comment]
@berte : I've finished the translation preparation phase i.e. all strings are now taken into account, including debug and help strings.

From the tr.po file, 42 are translated and 18 are not yet.
Can you please?:
- add the missing translated strings
- review the ones you've already done, as few of them have changed, and I made also some cleaning in the whitespaces

Thanks

**Comment by berte** [comment]
@valr sure I will, let me check

**Pull request merged**
